### ISSUE TITLE
RFC: Helpers directory

### ISSUE THREAD

**Issue by hanam1ni** [nimblehq/elixir-templates#121]
## Issue

I checked the module [NimbleTemplate.Template](https://github.com/nimblehq/elixir-templates/blob/develop/lib/nimble_template/template.ex) and I think some functions do not belong to this module. We can extract these functions into the helper module and group them in the `Helpers` directory.

![image](https://user-images.githubusercontent.com/14077479/129882939-10891078-69a1-485a-8896-c9ea30ea49d7.png)

## Solution

Introduce the `helpers` directory and we can place all helper functions there.

![image](https://user-images.githubusercontent.com/14077479/129883108-c545df25-924a-41b2-98f0-7ab1abb1e216.png)

## Who Benefits?

Developers

## What's Next?

- [ ] Create refactoring `NimbleTemplate.Template` PR

[![](https://api.gh-polls.com/poll/01FDCCZY549FEAD4FS0H3MXP66/Yes)](https://api.gh-polls.com/poll/01FDCCZY549FEAD4FS0H3MXP66/Yes/vote)
[![](https://api.gh-polls.com/poll/01FDCCZY549FEAD4FS0H3MXP66/No)](https://api.gh-polls.com/poll/01FDCCZY549FEAD4FS0H3MXP66/No/vote)

**Comment by andyduong1920** [comment]
👍 Micky
