### ISSUE TITLE
Don't commit the `prod.secret.exs` file to GIT

### ISSUE THREAD

**Issue by anduonghien** [nimblehq/elixir-templates#13]
## Feature request

As discussion with Olivier on this [comment](https://github.com/anduonghien/ex_marketer/pull/1#discussion_r454904323)

**Comment by hanam1ni** [comment]
I think we can commit this file, for Heroku if we set the env var and use `System.get_env` it will fetch from Heroku and not hardcode in the file 🤔

**Comment by anduonghien** [comment]
Yeah, @hanam1ni it's the same what I discussed with Olivier. That file is required if we release with non-container mode (like pushing code to Heroku like currently, we did) but for container mode, we no need that file ;)

**Comment by anduonghien** [comment]
I just check the document again, in the release mode, we still need that file 😂  just rename it to `config/releases.exs` 

https://hexdocs.pm/phoenix/releases.html

![image](https://user-images.githubusercontent.com/11751745/88265547-e76ead00-ccf7-11ea-943a-19f156cd7087.png)

**Comment by anduonghien** [comment]
I'm closing this issue cause we need that, but if we deploy with mix release then we need to change the file name to `release`. That will done on #12
