### ISSUE TITLE
RFC: Add Github Action Deployment Workflow 

### ISSUE THREAD

**Issue by byhbt** [nimblehq/elixir-templates#134]
## Issue

Integrating the workflow for deployment to AWS ECS or Heroku. By adding Github Actions Workflow to the template.

We have 2 open PRs:
- Heroku: https://github.com/nimblehq/elixir-templates/pull/101
- AWS ECS: https://github.com/nimblehq/elixir-templates/pull/125

## Solution

Add Github Actions for automating the deployment to ECS, Heroku... and other services.

## Who Benefits?

Developers.

## What's Next?

[![](https://api.gh-polls.com/poll/01FQE79D760TFMGTRKEVBHR5B1/Yes)](https://api.gh-polls.com/poll/01FQE79D760TFMGTRKEVBHR5B1/Yes/vote)
[![](https://api.gh-polls.com/poll/01FQE79D760TFMGTRKEVBHR5B1/No)](https://api.gh-polls.com/poll/01FQE79D760TFMGTRKEVBHR5B1/No/vote)

**Comment by andyduong1920** [comment]
Hi Thanh it does make sense to have these deploy workflow in the template, so later we can check the template later. As it's not the `infra code` so it's ok to have it.

I have merged 1 PR for the Heroku workflow, please open the workflow for ECS 🙏
