### ISSUE TITLE
Fix: Formatting issues when creating new API project

### ISSUE THREAD

**Issue by bterone** [nimblehq/elixir-templates#182]
## Issue

When creating a new project with the latest Phoenix Installer, the project runs into an issue with `prod.exs` when running `mix format`.

![Screen Shot 2022-03-28 at 12 44 14 PM](https://user-images.githubusercontent.com/34730459/160333751-1af0f842-04ff-4d61-8843-5a3721e5ab27.png)

Versions:
- Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
- Elixir 1.13.3 (compiled with Erlang/OTP 24)
- Phoenix Installer [`mix phx.new` ver.] v1.6.6
 
## Expected

The project can be formatted with no issues.
 
## Steps to reproduce

1. Create a new phoenix project with `mix phx.new` with the latest phoenix installer (1.6.6)
2. Add `{:nimble_template, "~> 4.1", only: :dev, runtime: false},` to `deps` in `mix.exs` as per instructions
3. `mix do deps.get, deps.compile`
4. Apply API variant `mix nimble_template.gen --api`, no addons are necessary.
5. Run `mix format`
6. Syntax error with `config/prod.exs` file.

**Comment by andyduong1920** [comment]
not sure as I can't reproduce it 🤔

![image](https://user-images.githubusercontent.com/11751745/160386866-f7f97c2e-c2ae-4f67-a908-a980c2162044.png)


Another thing, on the test the Apply the variant workflows we have the `Run mix codebase` step for the new generated application, we don't have any error on the `mix format` step there @bterone 

![image](https://user-images.githubusercontent.com/11751745/160387081-f146775d-0122-41e7-8209-e436b24f538a.png)

![image](https://user-images.githubusercontent.com/11751745/160387452-b6e940d8-a983-436b-a317-1b57b920e68e.png)

https://github.com/nimblehq/elixir-templates/runs/5718992570?check_suite_focus=true

**Comment by bterone** [comment]
What is the version of your `mix phx.new`? 🤔  @andyduong1920, is it 1.6.6?
I can always reproduce this error.

Also the `mix codebase` is our alias, it runs `credo, deps.unlock --check-unused` and `format`

**Comment by andyduong1920** [comment]
> What is the version of your `mix phx.new`? 🤔 @andyduong1920, is it 1.6.6? I can always reproduce this error.
> 
> Also the `mix codebase` is our alias, it runs `credo, deps.unlock --check-unused` and `format`

Oh true, that error happens when the application name is NOT long enough, I have fixed that on https://github.com/nimblehq/elixir-templates/pull/188
