### ISSUE TITLE
Fix: API Fallback controller is created in the incorrect folder

### ISSUE THREAD

**Issue by bterone** [nimblehq/elixir-templates#183]
## Issue

When creating an API project, the API fallback controller is generated in the incorrect folder
![Screen Shot 2022-03-28 at 4 35 17 PM](https://user-images.githubusercontent.com/34730459/160370341-d94ab363-3305-4f52-ae67-7dbf253adcc2.png)

## Expected

Should generate `fallback_controller.ex` into the `controllers/api` folder
 
## Steps to reproduce

1. Create a new phoenix project with `mix phx.new`
2. Add `{:nimble_template, "~> 4.1", only: :dev, runtime: false},` to `deps` in `mix.exs` as per instructions
3. `mix do deps.get, deps.compile`
4. Apply API variant `mix nimble_template.gen --api`, no optional addons are necessary.
5. Observe fallback controller generated in a newly created `controller` folder

**Note**: Possibly could be fixed by looking into `NimbleTemplate.Addons.Phoenix.Api.FallbackController`

![Screen Shot 2022-03-28 at 4 34 06 PM](https://user-images.githubusercontent.com/34730459/160370058-aeb23c94-dd64-4af9-8678-7050da2af27d.png)

**Comment by andyduong1920** [comment]
Is it a big @bterone 😂 is this fallback controller only for the API part, should it be in side the `controllers/api` folder 🤔

**Comment by bterone** [comment]
Yeah, It's just a small issue, as you mentioned @andyduong1920, it's supposed to be in the `controllers/api` folder. I've updated the description so it's more clear 👍 

I think just changing the [file path](https://github.com/nimblehq/elixir-templates/blob/develop/lib/nimble_template/addons/variants/phoenix/api/fallback_controller.ex#L20) of the fallback controller should resolve this one

**Comment by andyduong1920** [comment]
> Yeah, It's just a small issue, as you mentioned @andyduong1920, it's supposed to be in the `controllers/api` folder. I've updated the description so it's more clear 👍
> 
> I think just changing the [file path](https://github.com/nimblehq/elixir-templates/blob/develop/lib/nimble_template/addons/variants/phoenix/api/fallback_controller.ex#L20) of the fallback controller should resolve this one

Ah, got it, it should be `controllers/`` right @bterone

**Comment by andyduong1920** [comment]
@bterone FYI I opened a PR to fix this issue https://github.com/nimblehq/elixir-templates/pull/186/files
