### ISSUE TITLE
Fix: Replace config error when applying template

### ISSUE THREAD

**Issue by bterone** [nimblehq/elixir-templates#184]
## Issue

Raised a File Error when trying to apply the API template

![Screen Shot 2022-03-28 at 4 39 07 PM](https://user-images.githubusercontent.com/34730459/160374804-3ca612c2-6e80-42a1-9f04-345199f28ca0.png)

It seems some behavior is incorrectly modifying the `config/develop.exs` instead of `config/dev.exs`. Will require further investigation.
 
## Expected

Correctly apply replacement behavior to `config/dev.exs`.
 
## Steps to reproduce

1. Create a new phoenix project with `mix phx.new`
2. Add `{:nimble_template, "~> 4.1", only: :dev, runtime: false},` to `deps` in `mix.exs` as per instructions
3. `mix do deps.get, deps.compile`
4. Apply API variant `mix nimble_template.gen --api`, no optional addons are necessary.
5. Observe the error during the apply template step.

**Comment by andyduong1920** [comment]
I also saw that, it's generate from the 3rd library, hopefully in the upcoming version they will fix that :D

**Comment by bterone** [comment]
Oh, do we know from which 3rd party lib? @andyduong1920 👀

**Comment by andyduong1920** [comment]
Actually I found this error, changed it in https://github.com/nimblehq/elixir-templates/pull/188
