### ISSUE TITLE
Error during the generation of files on Phoenix version 1.6.7

### ISSUE THREAD

**Issue by liamstevens111** [nimblehq/elixir-templates#198]
## Issue

Error raised during the command 

```mix nimble_template.gen --web```

with the resulting error:

``` (Mix) Can't read test/support/channel_case.ex```

<img width="1291" alt="Screenshot 2565-04-27 at 12 54 44" src="https://user-images.githubusercontent.com/8955671/165466808-2cbb8bad-16a2-45ce-ac06-f145df7ec0bb.png">

The file **test/support/channel_case.ex** seems to have been removed in Phoenix version 1.6.7 and so the generation of files and subsequent questions do not occur.

[Link showing the Diff/Removal](https://www.phoenixdiff.org/?source=1.6.6&target=1.6.7)

## Expected
 
Questions are asked and files are generated according to the Nimble web template

## Steps to reproduce

1.  Generate a new Phoenix project with version 1.6.7 using **mix phx.new**
2. Add **{:nimble_template, "~> 4.1", only: :dev, runtime: false}** to mix.exs deps
3. Run **mix do deps.get, deps.compile**
4. Run **mix nimble_template.gen --web**

**Comment by andyduong1920** [comment]
Thanks for raising this @liamstevens111 it's because currently the template is tested on Phoenix 1.6.6 :) 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/11751745/165469809-750d7319-ee4e-4da3-9786-f0de4deaadb8.png">

**Comment by byhbt** [comment]
Should we upgrade it to support the latest version of Phoenix `1.6.11` instead of just supporting the version `1.6.7` @andyduong1920 ?

**Comment by andyduong1920** [comment]
> Should we upgrade it to support the latest version of Phoenix `1.6.11` instead of just supporting the version `1.6.7` @andyduong1920 ?

Sure, that make sense @byhbt 👍
