### ISSUE TITLE
Nginx integration

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/elixir-templates#20]

**Comment by caherrerapa** [comment]
Is Nginx actually the most common tool used for phoenix?

**Comment by andyduong1920** [comment]
I didn't check is Nginx is helpful with Phoenix yet, IMO Nginx could speed up some static request (image, css, js, fonts,...)

**Comment by byhbt** [comment]
The issue is migrated to Discussions section: https://github.com/nimblehq/elixir-templates/discussions/269
