### ISSUE TITLE
As a developer, I should be able to run all default tests without errors

### ISSUE THREAD

**Issue by Nihisil** [nimblehq/elixir-templates#202]
## Issue

If you are using a new laptop and generating new project with the `wallaby` plugin the tests after the `mix test` will fail with the error:

> \> mix test
> ** (MatchError) no match of right hand side value: {:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Wallaby.DependencyError{message: "Wallaby can't find chromedriver. Make sure you have chromedriver installed\nand included in your path.\nYou can also provide a path using `config :wallaby, :chromedriver, path: <path>`.\n"}, [{Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 33, error_info: %{module: Exception}]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 293]}]}}}}}}
>     test/test_helper.exs:9: (file)
>     (elixir 1.13.4) lib/code.ex:1183: Code.require_file/2
>     (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
> exit 1

It fails because [chromedriver](https://chromedriver.chromium.org/downloads) wasn't installed.

I checked both [laptop](https://github.com/nimblehq/laptop) and [elixir-templates](https://github.com/nimblehq/elixir-templates/) repositories, and didn't find any documentation related to installing `chromedriver`.
 
## Expected

Tests should be green after the project was set up or at least we need to list `chromedriver` in the documentation as prerequisites for a project.

**Comment by andyduong1920** [comment]
Hi @Nihisil we used to have that in the laptop install script before https://github.com/nimblehq/laptop/pull/3/files but it was removed, not sure the reason from there :D 

But yeah, we could add `chromedriver` as a prerequisite in the Readme.

**Comment by andyduong1920** [comment]
This issue is still open as we had an idea to improve it -> Check https://github.com/nimblehq/elixir-templates/pull/215#issuecomment-1162576077
