### ISSUE TITLE
Add formatter configuration for .heex files

### ISSUE THREAD

**Issue by Nihisil** [nimblehq/elixir-templates#207]
## Why

It is convenient to have a default formatter for `.heex` files as well, so you don't need to do it manually (or use a third-party tool).

Formatting requires Elixir `1.13.4`, which is greater than this template supported `1.13.3` version.

It was added in `phoenix_live_view`, `0.17.8` version: https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md#0178-2022-04-06

Instructions on how to set up you can find here: https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_formatter.ex

So, we can add this formatter feature once we update the template to the new Elixir version.

## Who Benefits?

Developers! Developers! Developers!

**Comment by andyduong1920** [comment]
@Nihisil FYI the https://github.com/nimblehq/elixir-templates/pull/229 will upgrade Elixir to `1.13.4` 

but to solve this issue, we need some tweaks in the `.formatter.exs` file to make that work

![image](https://user-images.githubusercontent.com/11751745/172831010-5f71a3bd-d0f0-445f-a3b2-da0186eee2c7.png)

Will keep you posted
