### ISSUE TITLE
Update testing Database seeds step to use `ENABLE_DB_SEED` env instead of `MIX_ENV: dev`

### ISSUE THREAD

**Issue by bterone** [nimblehq/elixir-templates#212]
## Why

Currently, it is the slowest step in the workflow.

![Screen Shot 2022-05-25 at 12 30 34 PM](https://user-images.githubusercontent.com/34730459/170186981-ac00da38-348e-478b-9bd7-fd587eec8176.png)

This is because when running that step, it would need to recompile the entire application in the `dev` ENV to perform that step

### Solution

Use some other ENV variable such as `ENABLE_DB_SEED` in the `test.yml` workflow instead of `MIX_ENV` and run seeds if set to true in `seeds.exs`

Changes already applied on the [WORPT project](https://github.com/worpt-wallet/wallet-api/pull/63/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R142) with massive improvements in time

![Screen Shot 2022-05-25 at 12 30 43 PM](https://user-images.githubusercontent.com/34730459/170186999-7be9dca8-2db9-4a6c-b9e4-1fc9bf49f043.png)

cc Thanks @rosle for the improvement 🙏 

## Who Benefits?

The whole world 🌏

**Comment by andyduong1920** [comment]
I see, it makes sense to use the ENV instead of compiling the dev dependencies @bterone cc @rosle will open a PR for that
