### ISSUE TITLE
Add `html_filter_full_covered` option to excoveralls

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/elixir-templates#240]
## Why

By default the `excoveralls` set `html_filter_full_covered` as false so files with 100% coverage is displaying in the HTML report.

With the large codebase, this is hard to find the `missed` test file as there is many files

![image](https://user-images.githubusercontent.com/11751745/182191403-eb824181-9201-4bdd-9849-cc0313ab16b0.png)

We could set the `html_filter_full_covered` to `true` so files with 100% coverage won't be displayed in the HTML report, the HTML report will include only the `missing` test files.

## Who Benefits?

Developer

**Comment by olivierobert** [comment]
I did not know about the option `html_filter_full_covered` 👍

**Comment by andyduong1920** [comment]
> I did not know about the option `html_filter_full_covered` 👍

Me too, it's just available since May 12 

https://github.com/parroty/excoveralls/commit/6482d8e0e4cc4a3d80a3cd7ab03cb28224fa8b8a

**Comment by liamstevens111** [comment]
https://github.com/parroty/excoveralls/releases/tag/v0.14.5

Yeah nice addition. I normally have to look at this file because the file it's reported as lacking coverage doesn't fit in the terminal as it's too long so I still have no idea what the file is.
