### ISSUE TITLE
[Chore] Resolve the Gettext warning in config

### ISSUE THREAD

**Issue by byhbt** [nimblehq/elixir-templates#252]
## Why

After generate new project which has `gettext`, the command line output this warning

```
warning: the :gettext compiler is no longer required in your mix.exs.

Please find the following line in your mix.exs and remove the :gettext entry:

    compilers: [..., :gettext, ...] ++ Mix.compilers(),

  (gettext 0.20.0) lib/mix/tasks/compile.gettext.ex:5: Mix.Tasks.Compile.Gettext.run/1
  (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
  (mix 1.13.4) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.13.4) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
  (mix 1.13.4) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
  (mix 1.13.4) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
```

## Who Benefits?

Elixir developer

**Comment by byhbt** [comment]
Related build failed:
- https://github.com/nimblehq/elixir-templates/runs/8268651960?check_suite_focus=true
- https://github.com/nimblehq/elixir-templates/runs/8268651960?check_suite_focus=true
- https://github.com/nimblehq/elixir-templates/runs/8268652500?check_suite_focus=true

**Comment by byhbt** [comment]
Look like the Phoenix team remove the `gettext` in `mix.exs` here: https://github.com/phoenixframework/phoenix/pull/4894 . But we not sure when It will be released, so at the moment it's a blocker to get the CI pass.

**Comment by hanam1ni** [comment]
@byhbt The issue about gettext is from the Phoenix generator itself that including the `:gettext` atom inside the fresh generated project. To fix the warning, we need to remove the atom until the Phoenix generator is fixed.

I can work on it 🙌

<img width="436" alt="image" src="https://user-images.githubusercontent.com/14077479/190353537-d3ee7639-7c51-45c9-9fea-c4e20bc47479.png">

**Comment by byhbt** [comment]
yes @hanam1ni ! Please help update it. 

I think we can fix it now to avoid blocking our CI and other feature related to it. In the future, when the new release of Phoenix is come out, then we can revert it.
