### ISSUE TITLE
[Chore] Add default `.iex.exs` file

### ISSUE THREAD

**Issue by byhbt** [nimblehq/elixir-templates#265]
## Why

The [.iex.exs](https://hexdocs.pm/iex/IEx.html#module-the-iex-exs-file) file is a "should have" convenience for developers. It could help developer save some typing effort when using the IEx to debug or experiment some functions in the codebase. 

Examples:
- Preload some common aliases: https://niallburkley.com/blog/preloading-aliases-in-iex/
- Predefined functions: https://gist.github.com/lukeledet/554ea994f71b9688179970669579efca

Todo:

- [ ] Add default `.iex.exs` file with `alias {WebApp}.Repo` at the root of the generated project.

Content of the `.iex.exs` file.

```elixir

# Load personal IEx config

import_file_if_available("~/.iex.exs")

import_if_available(Ecto.Query)

alias {WebApp}.Repo

IEx.configure(
  history_size: 1000,
  inspect: [
    pretty: true,
    limit: :infinity,
    charlists: :as_lists
  ],
  colors: [
    syntax_colors: [
      number: :light_yellow,
      atom: :light_cyan,
      string: :light_black,
      boolean: :red,
      nil: [:magenta, :bright]
    ],
    ls_directory: :cyan,
    ls_device: :yellow,
    doc_code: :green,
    doc_inline_code: :magenta,
    doc_headings: [:cyan, :underline],
    doc_title: [:cyan, :bright, :underline]
  ]
)

```
## Who Benefits?

Developers

**Comment by andyduong1920** [comment]
> The .iex.exs file is a "must have" convenience for developers

Might I know the source or benefit for `must have` @byhbt 🤔

**Comment by byhbt** [comment]
> > The .iex.exs file is a "must have" convenience for developers
> 
> Might I know the source or benefit for `must have` @byhbt 🤔

I think it's quite a convenience for developers, they can play around or test the functions, queries, or small pieces of code in the `Iex` shell. 

it can save some typing effort, by adding default `iex.exs` code as above.

Not too serious about the "must have" 😄 word, it's just a chore. btw, I update to the should have so don't confuse others

**Comment by andyduong1920** [comment]
> > > The .iex.exs file is a "must have" convenience for developers
> > 
> > 
> > Might I know the source or benefit for `must have` @byhbt 🤔
> 
> I think it's quite a convenience for developers, they can play around or test the functions, queries, or small pieces of code in the `Iex` shell.
> 
> it can save some typing effort, by adding default `iex.exs` code as above.
> 
> Not too serious about the "must have" 😄 word, it's just a chore. btw, I update to the should have so don't confuse others

Do we have any example for that @byhbt I'm curious how to use that, not sure how benefit is it

**Comment by byhbt** [comment]
Here are some examples of using `iex.exs`:

- https://hexdocs.pm/iex/IEx.html#module-the-iex-exs-file
- https://niallburkley.com/blog/preloading-aliases-in-iex/
- https://gist.github.com/lukeledet/554ea994f71b9688179970669579efca
- Or when we debug the application using `iex -S mix phx.server`, it also preloads some predefined aliases in `.iex.exs` (e.g: Repo)

**Comment by andyduong1920** [comment]
> Here are some examples of using `iex.exs`:
> 
>     * https://hexdocs.pm/iex/IEx.html#module-the-iex-exs-file
> 
>     * https://niallburkley.com/blog/preloading-aliases-in-iex/
> 
>     * https://gist.github.com/lukeledet/554ea994f71b9688179970669579efca
> 
>     * Or when we debug the application using `iex -S mix phx.server`, it also preloads some predefined aliases in `.iex.exs` (e.g: Repo)

Nice, I think you could add these links into the `Why` section so everyone will know that, also should we move this one to the Discussion 🤔

**Comment by byhbt** [comment]
> > Here are some examples of using `iex.exs`:
> > ```
> > * https://hexdocs.pm/iex/IEx.html#module-the-iex-exs-file
> > 
> > * https://niallburkley.com/blog/preloading-aliases-in-iex/
> > 
> > * https://gist.github.com/lukeledet/554ea994f71b9688179970669579efca
> > 
> > * Or when we debug the application using `iex -S mix phx.server`, it also preloads some predefined aliases in `.iex.exs` (e.g: Repo)
> > ```
> 
> Nice, I think you could add these links into the `Why` section so everyone will know that, also should we move this one to the Discussion 🤔

Yup, updated the description. ✅ 

Next time I will propose a new idea in the discussion. My idea was this `.iex.exs` is quite common use and supported by Elixir projects that why I created the issue with discussion.
