### ISSUE TITLE
Add `compass_credo_plugin` addon

### ISSUE THREAD

**Issue by byhbt** [nimblehq/elixir-templates#277]
## Why

Integrate [compass_credo_plugin](https://hex.pm/packages/compass_credo_plugin) to the ElixirTemplate.

https://hex.pm/packages/compass_credo_plugin

This library helps enforce [Nimble Elixir coding convention] (https://nimblehq.co/compass/development/code-conventions/elixir/) in the Elixir project.

## Who Benefits?

Developers

**Comment by hanam1ni** [comment]
Found some issues with this task. Can continue working on after #279 is fixed
