### ISSUE TITLE
Fix invalid disable Credo rule on not existing file

### ISSUE THREAD

**Issue by byhbt** [nimblehq/elixir-templates#307]
## Issue

When generating a new API project with the command `mix phx.new sample_project --no-html`, we got the message:

<img width="1058" alt="Screen Shot 2022-12-27 at 14 39 08" src="https://user-images.githubusercontent.com/948856/209629925-cd39243f-c843-4e57-b466-2480d19b69af.png">

Because the `--no-html` params won't create the `page_controller.ex` so the patching disable single expression failed. 

To prevent this case, we need to check if the file which is patching disable credo rule has existed in the existing codebase or not.

## Expected

The message should not be shown.
 
## Steps to reproduce

1. Create a new project with `mix phx.new sample_project --no-html`
1. Then apply `mix nimble_template.gen --api`

**Comment by liamstevens111** [comment]
Good catch, I thought I manually tested with `api` project too, guess I only did `mix` and `phoenix`, sorry about that.
