### ISSUE TITLE
Fix: Error when generating the web variant

### ISSUE THREAD

**Issue by nvminhtue** [nimblehq/elixir-templates#312]
## Issue

Extracting the bundle from `nimble_template v4.5.0` got an error of not resolving the `postcss-scss`
![image](https://user-images.githubusercontent.com/42540264/210329468-e46942fa-d1a1-4216-a875-14613147b74e.png)
and can't read some tests
![image](https://user-images.githubusercontent.com/42540264/210329523-4ed42a22-e88c-40dc-8308-c479a86660dd.png)
That leads to the interruption when running the `mix nimble_template.gen --web` script.
## Expected

The generation script should be run flawlessly.
 
## Steps to reproduce

1. Run `mix archive.install hex phx_new`
2. Initialize the phoenix project `mix phx.new awesome_project`
3. Add `{:nimble_template, "~> 4.5.0", only: :dev, runtime: false}` to the mix deps
4. Compile packages `mix do deps.get, deps.compile`
5. Generate the variant web by `mix nimble_template.gen --web`

**Comment by liamstevens111** [comment]
The file read errors should be fixed when `4.6` is released to hex (you can download the template locally and reference it in `deps.exs` to test that. 

Not sure on the sass part though

**Comment by andyduong1920** [comment]
@nvminhtue could you help to verify this issue again 🙏, we have just released the 4.6.0

**Comment by nvminhtue** [comment]
@andyduong1920 @liamstevens111 
It's working as expected now; thank you, guys.
