### ISSUE TITLE
Mix project variant?

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/elixir-templates#33]
Currently, the template is supporting the Phoenix project (API and web variants), how about supporting the Mix project (for creating another Elixir lib) 🤔

```
mix nimble.phx.gen.template --mix
```

We could consider changing the task name to `nimble.gen.template` so that doesn't contain the `phx` to make it clear

```
mix nimble.gen.template --mix
```

**Comment by olivierobert** [comment]
That would be a great addition as even for umbrella apps, we might not always need a Phoenix application. So I am in favour or renaming the task name to `mix nimble.gen.template`.
