### ISSUE TITLE
[RFC] Credo rules

### ISSUE THREAD

**Issue by Tolsee** [nimblehq/elixir-templates#4]
Add/update credo rules based on best practices and our preferences. Though the credo comes with the default config, some of the rules are better updated/tuned properly to increase productivity and consistency. 

#### `strict: true`
Set strict mode to true so that we can enforce the style guide.
<br/>
#### [`Credo.Check.Design.AliasUsage`](https://hexdocs.pm/credo/Credo.Check.Design.AliasUsage.html)
**Config:** 
```elixir
{Credo.Check.Design.AliasUsage,
  [
    priority: :low,
    if_nested_deeper_than: 2,
    if_called_more_often_than: 1
    excluded_namespaces: ~w[Ecto]
  ]
}
```

**Comment by olivierobert** [comment]
I am more in favor in enforcing usage of aliases as it helps to clearly see the dependencies of each module at the top of the file. Also, it would be better to consistently use aliases and not on a case by case basis.

Based on the [example](https://github.com/rrrene/credo/blob/master/lib/credo/check/design/alias_usage.ex):

```
# Better
defmodule MyApp.Web.Search do
  alias MyApp.External.TwitterAPI

  def twitter_mentions do
    TwitterAPI.search(...)
  end
end

# Less good
defmodule MyApp.Web.Search do
  def twitter_mentions do
    MyApp.External.TwitterAPI.search(...)
  end
end
```

**Comment by Tolsee** [comment]
Thanks @olivierobert 
Let's go with the your suggestion for `AliasUsage`

**Comment by andyduong1920** [comment]
Hi @Tolsee @olivierobert the AliasUsage seems didn't update in https://github.com/nimblehq/elixir-templates/pull/3/files#diff-78b22540b368040b6266f21dc737a6baR75 so I think to bring this issue up cc @rosle @bterone @hanam1ni 

We would need to look at 2 topics

1/ Using `credo --strict`mode
2/ Improve the `.credo.exs` in `priv/templates/nimble.phx.gen.template/.credo.exs`

**Comment by andyduong1920** [comment]
Implemented in https://github.com/nimblehq/elixir-templates/pull/31
