### ISSUE TITLE
Keeping the assets folder in the `root folder`?

### ISSUE THREAD

**Issue by anduonghien** [nimblehq/elixir-templates#7]
May I know the reason that we keep the `assets` folder in the root folder instead of putting it in the `nimble_web` folder, as I know, the `mix phx.new xxx --umbrella` command generates the `assets folder inside the xxx_web folder. Or it just for the case that we will have multiple web apps (like the public one and the admin one)

**Comment by olivierobert** [comment]
Duplicate of #6
