### ISSUE TITLE
JS and CSS Linters for the Web variant

### ISSUE THREAD

**Issue by olivierobert** [nimblehq/elixir-templates#85]
## Why

To enhance the Web variant of the template, we can extract the work done by @rosle in MindValley to set up CSS and JS linters:

The following can be added to `mix.exs`:

```
lint: [
  "format --check-formatted",
  "credo",
  "cmd ./assets/node_modules/.bin/eslint --color ./assets",
  "cmd ./assets/node_modules/.bin/stylelint --color ./assets/css"
],
"lint.fix": [
  "format",
  "cmd ./assets/node_modules/.bin/eslint --color --fix ./assets",
  "cmd ./assets/node_modules/.bin/stylelint --color --fix ./assets/css"
]
```
 With the following NPM dependencies:

![image](https://user-images.githubusercontent.com/696529/112121083-6bfc2d00-8bf1-11eb-9098-582d191a7996.png)

 
## Who Benefits?

Developers 💯

**Comment by andyduong1920** [comment]
We had the `mix codebase` which contain the `credo, format --check-formatted` already so I suggest adding the eslint and stylelint to the `codebase` alias @olivierobert and the same we can have the `codebase.fix` alias, what do you think?

**Comment by olivierobert** [comment]
Yes, that makes sense too @andyduong1920 👍
