### ISSUE TITLE
Remove repository template setting

### ISSUE THREAD

**Issue by byhbt** [nimblehq/elixir-templates#88]
As the repositories list, we can see it as the template repository, however I think it could confuse the developers because **Template** Repository is for a different purpose, according to the docs, the Template Repository for "generate new repositories with the same directory structure, branches, and files."

 Reference: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

<img width="1020" alt="Screen Shot 2021-03-28 at 4 25 23 PM" src="https://user-images.githubusercontent.com/948856/112747871-4b154c80-8fe2-11eb-9d38-4b596b73a7bb.png">

I would suggest we uncheck the Template Repository from the repository settings:
https://github.com/nimblehq/elixir-templates/settings

<img width="713" alt="Screen Shot 2021-03-28 at 4 19 47 PM" src="https://user-images.githubusercontent.com/948856/112747731-6b90d700-8fe1-11eb-82a9-b35d7168c314.png">

**Comment by andyduong1920** [comment]
Good catch @byhbt, I will change it now :)

**Comment by andyduong1920** [comment]
Oh I don't have permission to change that 😄 @olivierobert please help us to change that option 🙏

**Comment by olivierobert** [comment]
@byhbt @andyduong1920 I changed the repository setting. The Web Chapter has "Maintain" permissions which is the highest I can provide to the team :-)

**Comment by andyduong1920** [comment]
Thanks @olivierobert 👍 and @byhbt
